FROM node:22-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache \
    openssl \
    libc6-compat \
    bash  

COPY .env ./

COPY package*.json yarn.lock ./

COPY . .

RUN yarn install

EXPOSE 3000

CMD yarn migration:run && yarn run seed && yarn start:dev